<?php /* Smarty version 2.6.30, created on 2020-01-26 20:08:37
         compiled from header.tpl */

$this->_cache_serials['/var/www/html/Smarty/templates_c/%%F7^F7F^F7F34188%%header.tpl.inc'] = '4402ae6dcfe4d9bab1bf357cccd121c2';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('modifier', 'default', 'header.tpl', 117, false),array('modifier', 'escape', 'header.tpl', 134, false),array('function', 'dropdown_menu_video_categories', 'header.tpl', 359, false),array('function', 'dropdown_menu_article_categories', 'header.tpl', 388, false),)), $this); ?>
<?php
function _smarty_tplfunc_4402ae6dcfe4d9bab1bf357cccd121c2_0(&$_smarty)
{
echo smarty_art_html_list_categories(array('max_levels' => 3), $_smarty);
}



?>
