<?php /* Smarty version 2.6.30, created on 2019-04-23 12:30:44
         compiled from header.tpl */

$this->_cache_serials['/var/www/html/Smarty/templates_c/%%F7^F7F^F7F34188%%header.tpl.inc'] = '1e68f72e3df2e6c7ad0a16b67a0c386d';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('modifier', 'default', 'header.tpl', 85, false),array('modifier', 'escape', 'header.tpl', 102, false),array('function', 'dropdown_menu_video_categories', 'header.tpl', 326, false),array('function', 'dropdown_menu_article_categories', 'header.tpl', 334, false),)), $this); ?>
<?php
function _smarty_tplfunc_1e68f72e3df2e6c7ad0a16b67a0c386d_0(&$_smarty)
{
echo smarty_art_html_list_categories(array('max_levels' => 3), $_smarty);
}



?>
